### PR TITLE
Implement getByPath for files and folders

### PR DESCRIPTION
**Pull request by mattwiller**

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @mattwiller has signed the CLA. Thanks for the pull request!

**Comment by abarriel** [comment]
👍

**Comment by adamdavies001** [comment]
This needs to be reviewed and merged ASAP. A very useful feature to have.

**Comment by mattwiller** [comment]
Unfortunately, it's not just a matter of getting this PR reviewed.  The underlying API is not considered stable, and is currently not ready for GA.  For the time being, I'm going to close this PR to avoid confusing people about the status of this API.

**Pull request closed without merging**
