### PR TITLE
Change user login

### PR DESCRIPTION
**Pull request by Trudko**
Implementation, documentation and unit tests.

### CODE REVIEW

**Comment by mattwiller** [comment]
This functionality is already available as `users.update(userID, {login: emailAddress}, callback)`; I'm not sure we need an entirely different method for it, since it's a straightforward update call on the field.

**Comment by Trudko** [comment]
Could you please explain how do you decide when to add separate functions and when not? 

For example handling Get Current User Info and Get User Info by a same function seems clear - you want to get user info.

In this case I would argue that intentions behind changing user login are different enough than intentions behind updating other fields in a similar way how lock/unlock have different intention behind it that just simply updating other file parameter. 

Could you clarify how do you look at this and why for example lock and lock were separate functions from update a file?

**Comment by mattwiller** [comment]
@Trudko To me, the difference is in the complexity of the operation being performed.  For lock and unlock, the user would need to create a nested object, which isn't very intuitive for the operation.  I'd be open to doing the same thing for creating/removing shared links.  But for login, it's a straightforward update of a well-named field.  I'm not sure I understand how updating `login` is different from updating, say, `name`.

**Comment by Trudko** [comment]
@mattwiller thank you for the answer. I agree that if the we decide based on complexity of calling the method , then change user login and change user name are equivalent. So I can remove the implementation and update the comment.

**Pull request closed without merging**
