### PR TITLE
Add class level getBasicClient

### PR DESCRIPTION
**Pull request by cbetta**
This allows for simpler creation of a basic client, without the need to instantiate a dummy SDK first. See #276 for more information.

```
let Box = require('box-node-sdk');
let client = Box.getBasicClient(actualAccessToken);
```

(Attempt #2 /cc @mattwiller)

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @cbetta has signed the CLA. Thanks for the pull request!

**Comment by cbetta** [comment]
One remaining question: is there a reason the instance level `getBasicClient` exists as well? If so, should this class level one maybe be called something else?

**Comment by mattwiller** [comment]
@cbetta Thank you for the updated PR — this looks like it should work!  Unfortunately, your branch is failing CI due to lack of code coverage — would you mind adding a test to ensure that this method works correctly?  Something like [this existing test](https://github.com/box/box-node-sdk/blob/master/tests/integration-test.js#L58) would be great.

**Comment by cbetta** [comment]
@mattwiller have updated with a test. Still getting errors as a few dependencies have security issues, which I don't think should be fixed in this PR. Happy to pull those upstream changes when they go live.

**Comment by mattwiller** [comment]
@cbetta I just merged a fix for the security issues — I'll update your branch to re-run CI

**Pull request merged**
