### PR TITLE
Corrections to docs for enterprise event streaming

### PR DESCRIPTION
**Pull request by mself**

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @mself, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by mself** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @mself has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by mattwiller** [comment]
@mself This is the same branch you originally used for this change; I'm not sure how to deal with re-merging a branch that has already been merged.  Would you mind recreating the PR from a fresh branch off of master?

**Pull request merged**
