### PR TITLE
Require Promise in lib/token-manager.js and update jsonwebtoken

### PR DESCRIPTION
**Pull request by fgodino**

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @fgodino, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by fgodino** [comment]
CLA signed

**Comment by boxcla** [comment]
I couldn't find a signed CLA for @fgodino. Can you please try again?

**Comment by fgodino** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @fgodino has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by mattwiller** [comment]
Hi @fgodino — could you please give me some context around these changes?  I'm particularly concerned about the `jsonwebtoken` update, since there are a lot of breaking changes that probably need to be verified.  Is there a specific fix in the new version you care about?

**Comment by fgodino** [comment]
@mattwiller I just realized that the problem was due to a wrong resolved deep dependency in `jsonwebtoken`. I reverted those changes. The `bluebird` requirement is to avoid using native Promises.

**Pull request merged**
