### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by hochmanjoel**
The manual method did not work without the changes that I note in the README. Want to save someone from having to deal with this problem.

### CODE REVIEW

**Comment by sujaygarlanka** [comment]
@hochmanjoel I just tested the manual method shown in the docs and it worked for me. What version of the Node SDK are you on?

**Comment by hochmanjoel** [comment]
v14.5.0

**Comment by sujaygarlanka** [comment]
@hochmanjoel Our Node SDK version, not the Node environment version.

**Comment by hochmanjoel** [comment]
1.34.3

**Comment by sujaygarlanka** [comment]
@hochmanjoel I tried the configuration in our docs with the our most recent SDK version and it worked fine. Going to close this because we are not able to replicate it. Thank you for taking an interest in contributing to the SDK. Feel free to re-open this if you can post your code and want to pursue this further.

**Pull request closed without merging**
