### PR TITLE
fix broken links on auth doc

### PR DESCRIPTION
**Pull request by kienpham2000**

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @kienpham2000, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by kienpham2000** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @kienpham2000 has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by mattwiller** [comment]
@kienpham2000 Thanks for the PR!

**Pull request merged**
